# docker compose --profile all up -d
# docker compose --profile all down --remove-orphans
# docker compose logs -f mysql
# docker compose logs -f wordpress

# http://localhost:8080/

volumes:
  mysql_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/mysql_data"
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/wordpress_data"

networks:
  network_wordpress:
    name: network_analitics
    driver: bridge
    enable_ipv6: false

services:
  mysql:
    profiles: [ "all" ]
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      network_wordpress:
        aliases:
          - mysql

  wordpress:
    profiles: [ "all" ]
    #image: wordpress:php8.2-apache
    image: us-central1-docker.pkg.dev/local-volt-431316-m2/nogales/wordpress:2.0.1
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/html/wp-content
    networks:
      network_wordpress:
        aliases:
          - wordpress

